### ISSUE TITLE
Incorrect Answer 

### ISSUE THREAD

**Issue by Poperator** [EricAndrechek/FermiQuestions#26]
Q: How many generations back do you have to go until your total number of ancestors is equal to the world population?

A: It should be 30, as shown from where the question was sourced, but the answer that the website displays is 1.

**Comment by EricAndrechek** [comment]
@Haadi-Khan

**Comment by ahnoah** [comment]
30 = 3.0*10^1, so fermi answer is 1 (?)
definitely not 10^30 generations back if that's what the argument is

**Comment by EricAndrechek** [comment]
Ah @Poperator I misunderstood your questions but yes @ahnoah is correct. Check out the drop-down tab on the website explaining how fermi questions work. We don't care about the precise answer so much as we do the magnitude of the answer, so we take the power of ten as the answer. As @ahnoah explained, since the answer would have just been 30, it can be expressed as 3.0*10^1, giving us 1 as the answer. Hope this helps!

**Comment by Haadi-Khan** [comment]
> Ah @Poperator I misunderstood your questions but yes @ahnoah is correct. Check out the drop-down tab on the website explaining how fermi questions work. We don't care about the precise answer so much as we do the magnitude of the answer, so we take the power of ten as the answer. As @ahnoah explained, since the answer would have just been 30, it can be expressed as 3.0*10^1, giving us 1 as the answer. Hope this helps!

So we can close this issue?
