### ISSUE TITLE
Wording of "mass of mars in iphone 5s"

### ISSUE THREAD

**Issue by ZeliTheZealot** [EricAndrechek/FermiQuestions#29]
Please change the wording to "what is the mass of the planet Mars divided by the mass of an iPhone 5".

**Comment by EricAndrechek** [comment]
I kind of like the original question as it requires you to think a bit more about what it is asking, rather than it holding your hand and walking you through how to solve the problem with division. If more people disagree and think it should not be as it is currently, they may feel free to express those thoughts here and I can make said changes.
